-- Seed 39 societies (unverified seeds, NOT official active list)
insert into public.societies (name, slug, category, description, accent_color, verified) values
('Ashwamedh','ashwamedh','cultural','The Dramatics Society','#f43f5e', false),
('Crescendo','crescendo','cultural','The Music Society','#8b5cf6', false),
('Junoon','junoon','cultural','The Photography Club','#06b6d4', false),
('Mirage','mirage','cultural','Western Dance Crew','#ec4899', false),
('Canvas','canvas','cultural','Fine Arts Society','#f59e0b', false),
('Clitch','clitch','cultural','Fashion Society','#d946ef', false),
('Shakesjeer','shakesjeer','cultural','Open Mic','#14b8a6', false),
('THC','thc','cultural','Travel and Hiking Club','#22c55e', false),
('SPIC MACAY NSUT','spic-macay','cultural','Society for Promotion of Indian Classical Music and Culture','#eab308', false),
('CSI NSUT','csi','technical','Computer Society of India','#3b82f6', false),
('IEEE NSUT','ieee','technical','Advancing technology and innovation.','#0ea5e9', false),
('Devcomm','devcomm','technical','Developer Community','#6366f1', false),
('ARES','ares','technical','Robotics Society','#ef4444', false),
('The Debugging Society','debugging-society','technical','Coding community','#10b981', false),
('Nakshatra','nakshatra','technical','Astronomy and Mathematics','#818cf8', false),
('GDG NSUT','gdg','technical','Google Developer Groups','#fbbc04', false),
('Enactus NSUT','enactus','business','Social entrepreneurship','#eab308', false),
('FES','fes','business','Finance and Economics Society','#22c55e', false),
('E-Cell NSUT','e-cell','business','Entrepreneurship Cell','#f97316', false),
('TEDxNSUT','tedxnsut','business','Ideas worth spreading','#eb0028', false),
('180 Degrees Consulting','180dc','business','Consulting society','#0ea5e9', false),
('Alliance','alliance','literary','NSUT Newspaper','#64748b', false),
('Crosslinks','crosslinks','media','Media society','#8b5cf6', false),
('DebSoc NSUT','debsoc','literary','Debating Society','#f43f5e', false),
('NSUT Quiz Club','quiz-club','literary','Quizzing community','#06b6d4', false),
('Aagaaz','aagaaz','literary','Poetry Society','#d946ef', false),
('Tatsam','tatsam','literary','Hindi Society','#f59e0b', false),
('Axiom','axiom','literary','Philosophy Society','#94a3b8', false),
('Intaglios','intaglios','media','Design Society','#ec4899', false),
('Rotaract','rotaract','social','Community service','#e11d48', false),
('NSS','nss','social','National Service Scheme','#2563eb', false),
('Prayas','prayas','social','Social initiative','#16a34a', false),
('Bullet Hawk Racing','bullet-hawk','automotive','Automotive team','#dc2626', false),
('NSUT Motorsports','motorsports','automotive','Motorsports team','#ea580c', false),
('Team Kalpana','team-kalpana','automotive','Engineering team','#7c3aed', false),
('NSUT Sports','sports','sports','Sports community','#22c55e', false),
('Moksha','moksha','fests','Annual cultural fest','#a855f7', false),
('Innovision','innovision','fests','Technical fest','#0ea5e9', false),
('Resonanz','resonanz','fests','Campus organization','#f43f5e', false)
on conflict (slug) do nothing;
